version: '3'
services:
  ovehub-ove-asset-manager-service:
    image: ovehub/ove-asset-manager-service:${SERVICE_VERSION}
    build:
      context: .
      dockerfile: docker/am/Dockerfile
    ports:
      - "6080:6080"
    volumes:
      - ./config/:/code/config/:ro
    environment:
      GUNICORN_THREADS: "8"
      SERVICE_LOG_LEVEL: "debug"

  ovehub-ove-asset-manager-proxy:
    image: ovehub/ove-asset-manager-proxy:${SERVICE_VERSION}
    build:
      context: .
      dockerfile: docker/proxy/Dockerfile
    ports:
      - "6081:6081"
    volumes:
      - ./config/:/code/config/:ro
    environment:
      GUNICORN_THREADS: "8"
      SERVICE_LOG_LEVEL: "debug"

  ovehub-ove-asset-manager-worker-zip:
    image: ovehub/ove-asset-manager-worker-zip:${SERVICE_VERSION}
    build:
      context: .
      dockerfile: docker/worker-zip/Dockerfile
    environment:
      SERVICE_LOG_LEVEL: "debug"
      SERVICE_AM_HOSTNAME: "ovehub-ove-asset-manager-service"
      SERVICE_AM_PORT: "6080"


  ovehub-ove-asset-manager-worker-dzi:
    image: ovehub/ove-asset-manager-worker-dzi:${SERVICE_VERSION}
    build:
      context: .
      dockerfile: docker/worker-dzi/Dockerfile
    environment:
      SERVICE_LOG_LEVEL: "debug"
      SERVICE_AM_HOSTNAME: "ovehub-ove-asset-manager-service"
      SERVICE_AM_PORT: "6080"


  ovehub-ove-asset-manager-worker-tulip:
    image: ovehub/ove-asset-manager-worker-tulip:${SERVICE_VERSION}
    build:
      context: .
      dockerfile: docker/worker-tulip/Dockerfile
    environment:
      SERVICE_LOG_LEVEL: "debug"
      SERVICE_AM_HOSTNAME: "ovehub-ove-asset-manager-service"
      SERVICE_AM_PORT: "6080"


  ovehub-ove-asset-manager-ui:
    image: ovehub/ove-asset-manager-ui:${SERVICE_VERSION}
    build:
      context: .
      dockerfile: docker/ui/Dockerfile
    ports:
      - "6060:6060"
    environment:
      SERVICE_LOG_LEVEL: "debug"
      SERVICE_AM_HOSTNAME: "ovehub-ove-asset-manager-service"
      SERVICE_AM_PORT: "6080"